### ISSUE TITLE
Fedora 27 missing library

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armorbench1#1]
Hello, i'm testing Armory in new Linux PC ( Fedora 27 ) but i cannot run armorbench1 preview 2 :

`./_run: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`\

Cannot find and install easily the libcrypto.so.1.0.0 library with dnf, could you add it as static library or suggest another  #solution?

**Comment by luboslenco** [comment]
Does running any Armory project from Blender using the Krom runtime work on your new setup? If so you should be able to clone one of the [older commits](https://github.com/armory3d/armorbench1/commits/master) and run from Blender.

Preview 2 commit: https://github.com/armory3d/armorbench1/commit/00ac8e405130d1f19703793070b740e63b36d7f7.

**Comment by AndreaMonzini** [comment]
Hello i did some tests with screenshots and  where possible you can see the Render Path:

System used: Armory01_linux  with Fedora 27, AMDGPU with RX 580 + Ryzen 7 @3.5

Default cube with Krom Deferred ( there are graphic glitches on the top border):

![screenshot from 2018-01-17 13-42-25](https://user-images.githubusercontent.com/12413409/35044292-1d2707da-fb90-11e7-9922-7dfdd9966cd0.png)

Default cube with Krom Forward
![screenshot from 2018-01-17 13-42-51](https://user-images.githubusercontent.com/12413409/35044300-24c3eb52-fb90-11e7-9133-f4c9112d009b.png)

armorbech 1  Deferred Max Render GI Off (graphic glitches and ghost effects)
![screenshot from 2018-01-17 13-59-10](https://user-images.githubusercontent.com/12413409/35044343-52ba82d2-fb90-11e7-8541-dd01e10caa30.png)
![screenshot from 2018-01-17 13-59-06](https://user-images.githubusercontent.com/12413409/35044393-82b083d8-fb90-11e7-950f-2f76b3a44d40.png)
armorbech 1  Deferred Max Render With Global illumination GI
![screenshot from 2018-01-17 13-38-16](https://user-images.githubusercontent.com/12413409/35044375-70ad4fa4-fb90-11e7-81e7-66caefcbc77a.png)

armorbech 1 with broswer demo, as soon i move the mouse everything become burned white:
![screenshot from 2018-01-17 13-34-26](https://user-images.githubusercontent.com/12413409/35044406-8edc2446-fb90-11e7-9801-e6733b2aca3e.png)
![screenshot from 2018-01-17 13-34-32](https://user-images.githubusercontent.com/12413409/35044408-9095e434-fb90-11e7-859c-50334059f553.png)

Other graphic glitches with forwad and low:

![screenshot from 2018-01-17 14-17-27](https://user-images.githubusercontent.com/12413409/35044617-673dbb2e-fb91-11e7-9146-946073b4e783.png)
![screenshot from 2018-01-17 14-18-04](https://user-images.githubusercontent.com/12413409/35044626-6ee20db2-fb91-11e7-9279-43d491136526.png)

Publishing:

When i try to "Play"  Krom ( not in viewport) nothing happen...
I see the Krom build but how i can test outside the Viewport? ( i'm not Linux expert )


HTML5 deferred doesn't work but forward seems to work well :)

![screenshot from 2018-01-17 13-44-32](https://user-images.githubusercontent.com/12413409/35044700-a782b856-fb91-11e7-9901-c74ea1edd646.png)

I see also a strange texture as reflection :)

![screenshot from 2018-01-17 14-29-36](https://user-images.githubusercontent.com/12413409/35045126-1a6e05f4-fb93-11e7-8474-435ed33a0e1b.png)

**Comment by luboslenco** [comment]
Heyho,

It is not possible to run GI in b2.79 viewport or browser, some more [details](http://armory3d.org/manual/graphics/global_illumination.html). Armory v0.2 auto-disables GI on unsupported targets, so hopefully less trouble there.

Playing in Krom - a window should pop up like usual. What is the terminal output? What error do you get?

**Comment by AndreaMonzini** [comment]
I tested Armory with Blender 2.8 and Voxel GI works in the viewport, thanks!
i have graphic glitches on the borders with other examples and simple deferred ( no Max Game and no GI) 

![screenshot from 2018-01-17 14-37-07](https://user-images.githubusercontent.com/12413409/35045609-acd8813e-fb94-11e7-8b77-bbdca5cc7bbf.png)

while this is the terminal report after i click Play with Krom but i see also several `DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument`
`
[linux@localhost Armory]$ ./blender
Color management: using fallback mode for management
Read prefs: /home/linux/.config/blender/2.79/config/userpref.blend
found bundled python: /home/linux/App/Armory/Armory01_linux/Armory/2.79/python
Read blend: /home/linux/App/Armory/armorbench1-master/armorbench.blend
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0

Armory v0.1.0 ($Id: 9977a571ccfab9e8e2e587c2a8e02abe843ab21d $)
OS: linux, Target: krom, GAPI: opengl
Exporting Scene
Exporting object action FlashlightAction
Scene built in 0.21151518821716309
Exported modules: ['physics', 'ui']
Shader flags: ['_Irr', '_EnvTex', '_Rad', '_CSM', '_SMAA', '_SSAO']
Running:  ['/home/linux/App/Armory/Armory01_linux/Armory/armsdk//nodejs/node-linux64', '/home/linux/App/Armory/Armory01_linux/Armory/armsdk//linux64/resources/app/extensions/kha/Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--to', 'build_armorbench/debug']
Using Kha from /home/linux/App/Armory/Armory01_linux/Armory/armsdk/linux64/resources/app/extensions/kha/Kha
Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (Barrel_data.arm).
Exporting asset 1 of 1 (Barrel_Rim_data.arm).
Exporting asset 1 of 1 (Handle_data.arm).
Exporting asset 1 of 1 (MaterialUI_data.arm).
Exporting asset 1 of 1 (Material_001_data.arm).
Exporting asset 1 of 1 (Material_003_data.arm).
Exporting asset 1 of 1 (Material_004_data.arm).
Exporting asset 1 of 1 (Material_006_data.arm).
Exporting asset 1 of 1 (Material_008_data.arm).
Exporting asset 1 of 1 (Material_009_data.arm).
Exporting asset 1 of 1 (Material_021_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (mat1_blue_data.arm).
Exporting asset 1 of 1 (blur_adaptive_pass.arm).
Exporting asset 1 of 1 (blur_edge_pass.arm).
Exporting asset 1 of 1 (compositor_pass.arm).
Exporting asset 1 of 1 (smaa_blend_weight.arm).
Exporting asset 1 of 1 (smaa_edge_detect.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend.arm).
Exporting asset 1 of 1 (ssao_pass.arm).
Exporting asset 1 of 1 (ssr_pass.arm).
Exporting asset 1 of 1 (world.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (hall.hdr).
Exporting asset 1 of 1 (scuffed-plastic-ao.jpg).
Exporting asset 1 of 1 (scuffed-plastic-normal.jpg).
Exporting asset 1 of 1 (scuffed-plastic-rough.jpg).
Exporting asset 1 of 1 (scuffed-plastic4-alb.jpg).
Exporting asset 1 of 1 (scuffed-plastic5-alb.jpg).
Exporting asset 1 of 1 (wall_b.jpg).
Exporting asset 1 of 1 (wall_m.jpg).
Exporting asset 1 of 1 (wall_n.jpg).
Exporting asset 1 of 1 (wall_r.jpg).
Exporting asset 1 of 1 (lenstexture.jpg).
Exporting asset 1 of 1 (ui_persp.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (hall_irradiance.arm).
Exporting asset 1 of 1 (hall_radiance.hdr).
Exporting asset 1 of 1 (hall_radiance_0.hdr).
Exporting asset 1 of 1 (hall_radiance_1.hdr).
Exporting asset 1 of 1 (hall_radiance_2.hdr).
Exporting asset 1 of 1 (hall_radiance_3.hdr).
Exporting asset 1 of 1 (hall_radiance_4.hdr).
Exporting asset 1 of 1 (hall_radiance_5.hdr).
Exporting asset 1 of 1 (hall_radiance_6.hdr).
Exporting asset 1 of 1 (hall_radiance_7.hdr).
Exporting asset 1 of 1 (hall_radiance_8.hdr).
Exporting asset 1 of 1 (hall_radiance_9.hdr).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (action_FlashlightAction.arm).
Exporting asset 1 of 1 (mesh_Barrel_Bolts_Mesh.arm).
Exporting asset 1 of 1 (mesh_Circle.033.arm).
Exporting asset 1 of 1 (mesh_Cube.002.arm).
Exporting asset 1 of 1 (mesh_Cylinder.001.arm).
Exporting asset 1 of 1 (mesh_Cylinder.002.arm).
Exporting asset 1 of 1 (mesh_Cylinder.005.arm).
Exporting asset 1 of 1 (mesh_Cylinder.arm).
Exporting asset 1 of 1 (mesh_Plane.000.arm).
Exporting asset 1 of 1 (mesh_Plane.001.arm).
Exporting asset 1 of 1 (mesh_Plane.002.arm).
Exporting asset 1 of 1 (mesh_Plane.003.arm).
Exporting asset 1 of 1 (mesh_Plane.004.arm).
Exporting asset 1 of 1 (mesh_Plane.005.arm).
Exporting asset 1 of 1 (mesh_Plane.006.arm).
Exporting asset 1 of 1 (mesh_Plane.008.arm).
Exporting asset 1 of 1 (mesh_Plane.019.arm).
Exporting asset 1 of 1 (mesh_Untitled.000.arm).
Exporting asset 1 of 1 (mesh_Untitled.001.arm).
Exporting asset 1 of 1 (mesh_Untitled.003.arm).
Exporting asset 1 of 1 (mesh_Untitled.004.arm).
Exporting asset 1 of 1 (droid_sans.ttf).
Compiling shader 1 of 1 (Barrel_depth.frag.glsl).
Compiling shader 1 of 1 (Barrel_depth.vert.glsl).
Compiling shader 1 of 1 (Barrel_mesh.frag.glsl).
Compiling shader 1 of 1 (Barrel_mesh.vert.glsl).
Compiling shader 1 of 1 (Barrel_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Barrel_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Barrel_Rim_depth.frag.glsl).
Compiling shader 1 of 1 (Barrel_Rim_depth.vert.glsl).
Compiling shader 1 of 1 (Barrel_Rim_mesh.frag.glsl).
Compiling shader 1 of 1 (Barrel_Rim_mesh.vert.glsl).
Compiling shader 1 of 1 (Barrel_Rim_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Barrel_Rim_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Handle_depth.frag.glsl).
Compiling shader 1 of 1 (Handle_depth.vert.glsl).
Compiling shader 1 of 1 (Handle_mesh.frag.glsl).
Compiling shader 1 of 1 (Handle_mesh.vert.glsl).
Compiling shader 1 of 1 (MaterialUI_depth.frag.glsl).
Compiling shader 1 of 1 (MaterialUI_depth.vert.glsl).
Compiling shader 1 of 1 (MaterialUI_mesh.frag.glsl).
Compiling shader 1 of 1 (MaterialUI_mesh.vert.glsl).
Compiling shader 1 of 1 (MaterialUI_shadowmap.frag.glsl).
Compiling shader 1 of 1 (MaterialUI_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_001_depth.frag.glsl).
Compiling shader 1 of 1 (Material_001_depth.vert.glsl).
Compiling shader 1 of 1 (Material_001_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_001_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_003_depth.frag.glsl).
Compiling shader 1 of 1 (Material_003_depth.vert.glsl).
Compiling shader 1 of 1 (Material_003_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_003_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_003_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_003_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_004_depth.frag.glsl).
Compiling shader 1 of 1 (Material_004_depth.vert.glsl).
Compiling shader 1 of 1 (Material_004_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_004_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_004_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_004_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_006_depth.frag.glsl).
Compiling shader 1 of 1 (Material_006_depth.vert.glsl).
Compiling shader 1 of 1 (Material_006_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_006_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_006_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_006_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_008_depth.frag.glsl).
Compiling shader 1 of 1 (Material_008_depth.vert.glsl).
Compiling shader 1 of 1 (Material_008_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_008_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_008_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_008_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_009_depth.frag.glsl).
Compiling shader 1 of 1 (Material_009_depth.vert.glsl).
Compiling shader 1 of 1 (Material_009_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_009_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_009_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_009_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_021_depth.frag.glsl).
Compiling shader 1 of 1 (Material_021_depth.vert.glsl).
Compiling shader 1 of 1 (Material_021_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_021_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_021_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_021_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_depth.frag.glsl).
Compiling shader 1 of 1 (armdefault_depth.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 1 (mat1_blue_depth.frag.glsl).
Compiling shader 1 of 1 (mat1_blue_depth.vert.glsl).
Compiling shader 1 of 1 (mat1_blue_mesh.frag.glsl).
Compiling shader 1 of 1 (mat1_blue_mesh.vert.glsl).
Compiling shader 1 of 1 (mat1_blue_shadowmap.frag.glsl).
Compiling shader 1 of 1 (mat1_blue_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_adaptive_pass.frag.glsl).
Compiling shader 1 of 1 (blur_adaptive_pass.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass.vert.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 1 of 1 (ssao_pass.frag.glsl).
Compiling shader 1 of 1 (ssao_pass.vert.glsl).
Compiling shader 1 of 1 (ssr_pass.frag.glsl).
Compiling shader 1 of 1 (ssr_pass.vert.glsl).
Compiling shader 1 of 1 (world.frag.glsl).
Compiling shader 1 of 1 (world.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.vert.glsl).
Compiling shader 5 of 8 (painter-image.vert.glsl).
Compiling shader 6 of 8 (painter-text.frag.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-video.frag.glsl).
Done.
`

**Comment by AndreaMonzini** [comment]
In Blender 2.8 i have same border problems with deferred

i keep testing the graphic glitches on the borders with deferred and i discovered that changing the brackgound i have these behaviours:

Background OFF
![screenshot from 2018-01-17 15-04-24](https://user-images.githubusercontent.com/12413409/35046715-171096c4-fb98-11e7-9662-63638898cc0a.png)
Background WORLD
![screenshot from 2018-01-17 15-00-49](https://user-images.githubusercontent.com/12413409/35046728-1f24071a-fb98-11e7-8e21-10a356b639b6.png)
Background CLEAR
![screenshot from 2018-01-17 15-03-55](https://user-images.githubusercontent.com/12413409/35046733-24a837ba-fb98-11e7-94c3-f8e5e58b33a5.png)


:

**Comment by luboslenco** [comment]
I see. Tested navmesh example and no border glitches here, looks like I need to install another Linux distro.:( Or maybe the difference is caused by amd gpu, will see! Apparently GPUs are now also super over-priced to make the matters worse..

Also no error when playing krom is weird, I assume it's the `libcrypto.so.1.0.0` missing.

`Background OFF` means the backbuffer will not get cleared to save some frame time on desktop platforms. It should only be used when the background is completely occluded by scene geometry. The background is glitched because it's not cleared. I assume it's the same error in space corridor scene with the ui-panel - it's not cleared properly.

**Comment by AndreaMonzini** [comment]
Thank you for the support !
What Linux distro are you using?
I plan to install Debian testing  on different SSD.

**Comment by luboslenco** [comment]
Thank you for creating issue! I tested on Manjaro + xfce + proprietary nvidia driver, appears to be ok:
![screenshot_2018-01-17_15-31-32](https://user-images.githubusercontent.com/3685704/35047999-04a94cfc-fb9c-11e7-9835-56ba4f328e4e.png)

**Comment by AndreaMonzini** [comment]
Ok, as soon as possible, to help the testing i will install Manjaro too and i will report the results!

**Comment by luboslenco** [comment]
Oh that's awesome, thanks a ton for all the help!

**Comment by AndreaMonzini** [comment]
I tried to install Manjaro + xfce but i had problem with the installation using "MultiBootUsb", i will try in next days using directly the dd command. 

As soon as i'm able to install Manjaro + xfce i will report here.
